---
- name: Add nginx pkg repo
  apt_repository: repo="ppa:nginx/stable"

- name: Install system packages
  apt: name="{{ item }}" update_cache=yes state=present
  with_items:
    - gcc
    - g++
    - curl
    - wget
    - unzip
    - git
    - python-dev
    - python-apt
    - make
    - automake
    - autoconf
    - libreadline-dev
    - libncurses-dev
    - libssl-dev
    - libyaml-dev
    - libxslt-dev
    - libffi-dev
    - libtool
    - nginx
    - unixodbc-dev
    - monit
    - vim
    - python-pip
    - build-essential