---
- name: Add nodejs {{ nodejs_version }} repo
  apt_repository:
    repo: '{{ item.repo }}'
    state: present
    filename: nodesource
  with_items:
    - { repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }} trusty main' }
    - { repo: 'deb-src https://deb.nodesource.com/node_{{ nodejs_version }} trusty main' }
  become: yes

- name: Add apt signing key for nodejs
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: yes

- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes
    state: present
    force: yes
  become: yes
